sonar.projectKey=HealthcareApp
sonar.working.directory=C:\\Users\\310511\\source\\repos\\HealthcareApp\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=C:\\Users\\310511\\source\\repos\\HealthcareApp
sonar.pullrequest.cache.basepath=C:\\Users\\310511\\source\\repos\\HealthcareApp

151EF4F4-9CEA-BFCF-E0FE-EEFF8141403C.sonar.projectKey=HealthcareApp:151EF4F4-9CEA-BFCF-E0FE-EEFF8141403C
151EF4F4-9CEA-BFCF-E0FE-EEFF8141403C.sonar.projectName=HealthcareApp
151EF4F4-9CEA-BFCF-E0FE-EEFF8141403C.sonar.projectBaseDir=C:\\Users\\310511\\source\\repos\\HealthcareApp
151EF4F4-9CEA-BFCF-E0FE-EEFF8141403C.sonar.sourceEncoding=utf-8
151EF4F4-9CEA-BFCF-E0FE-EEFF8141403C.sonar.tests=
151EF4F4-9CEA-BFCF-E0FE-EEFF8141403C.sonar.sources=\
"C:\\Users\\310511\\source\\repos\\HealthcareApp\\Controllers\\AppointmentController.cs",\
"C:\\Users\\310511\\source\\repos\\HealthcareApp\\Controllers\\DoctorController.cs",\
"C:\\Users\\310511\\source\\repos\\HealthcareApp\\Controllers\\HealthRecordController.cs",\
"C:\\Users\\310511\\source\\repos\\HealthcareApp\\Controllers\\PatientController.cs",\
"C:\\Users\\310511\\source\\repos\\HealthcareApp\\Controllers\\SystemTimeController.cs",\
"C:\\Users\\310511\\source\\repos\\HealthcareApp\\Data\\DataStore.cs",\
"C:\\Users\\310511\\source\\repos\\HealthcareApp\\Enums\\AppointmentStatus.cs",\
"C:\\Users\\310511\\source\\repos\\HealthcareApp\\Enums\\Gender.cs",\
"C:\\Users\\310511\\source\\repos\\HealthcareApp\\Enums\\Specialisation.cs",\
"C:\\Users\\310511\\source\\repos\\HealthcareApp\\Exceptions\\AppointmentConflictException.cs",\
"C:\\Users\\310511\\source\\repos\\HealthcareApp\\Exceptions\\AppointmentNotFoundException.cs",\
"C:\\Users\\310511\\source\\repos\\HealthcareApp\\Exceptions\\DoctorNotFoundException.cs",\
"C:\\Users\\310511\\source\\repos\\HealthcareApp\\Exceptions\\DoctorUnavailableException.cs",\
"C:\\Users\\310511\\source\\repos\\HealthcareApp\\Exceptions\\DuplicateHealthRecordException.cs",\
"C:\\Users\\310511\\source\\repos\\HealthcareApp\\Exceptions\\InvalidAppointmentStatusException.cs",\
"C:\\Users\\310511\\source\\repos\\HealthcareApp\\Exceptions\\InvalidHealthRecordException.cs",\
"C:\\Users\\310511\\source\\repos\\HealthcareApp\\Exceptions\\NoHealthRecordsFoundException.cs",\
"C:\\Users\\310511\\source\\repos\\HealthcareApp\\Exceptions\\PastDateException.cs",\
"C:\\Users\\310511\\source\\repos\\HealthcareApp\\Exceptions\\PatientNotFoundException.cs",\
"C:\\Users\\310511\\source\\repos\\HealthcareApp\\Models\\Appointment.cs",\
"C:\\Users\\310511\\source\\repos\\HealthcareApp\\Models\\Doctor.cs",\
"C:\\Users\\310511\\source\\repos\\HealthcareApp\\Models\\HealthRecord.cs",\
"C:\\Users\\310511\\source\\repos\\HealthcareApp\\Models\\Patient.cs",\
"C:\\Users\\310511\\source\\repos\\HealthcareApp\\Program.cs",\
"C:\\Users\\310511\\source\\repos\\HealthcareApp\\Repositories\\IAppointmentRepository.cs",\
"C:\\Users\\310511\\source\\repos\\HealthcareApp\\Repositories\\IDoctorRepository.cs",\
"C:\\Users\\310511\\source\\repos\\HealthcareApp\\Repositories\\IHealthRecordRepository.cs",\
"C:\\Users\\310511\\source\\repos\\HealthcareApp\\Repositories\\Implementations\\AppointmentRepository.cs",\
"C:\\Users\\310511\\source\\repos\\HealthcareApp\\Repositories\\Implementations\\DoctorRepository.cs",\
"C:\\Users\\310511\\source\\repos\\HealthcareApp\\Repositories\\Implementations\\HealthRecordRepository.cs",\
"C:\\Users\\310511\\source\\repos\\HealthcareApp\\Repositories\\Implementations\\PatientRepository.cs",\
"C:\\Users\\310511\\source\\repos\\HealthcareApp\\Repositories\\IPatientRepository.cs",\
"C:\\Users\\310511\\source\\repos\\HealthcareApp\\Services\\IAppointmentService.cs",\
"C:\\Users\\310511\\source\\repos\\HealthcareApp\\Services\\IDoctorService.cs",\
"C:\\Users\\310511\\source\\repos\\HealthcareApp\\Services\\IHealthRecordService.cs",\
"C:\\Users\\310511\\source\\repos\\HealthcareApp\\Services\\Implementations\\AppointmentService.cs",\
"C:\\Users\\310511\\source\\repos\\HealthcareApp\\Services\\Implementations\\DoctorService.cs",\
"C:\\Users\\310511\\source\\repos\\HealthcareApp\\Services\\Implementations\\HealthRecordService.cs",\
"C:\\Users\\310511\\source\\repos\\HealthcareApp\\Services\\Implementations\\PatientService.cs",\
"C:\\Users\\310511\\source\\repos\\HealthcareApp\\Services\\IPatientService.cs",\
"C:\\Users\\310511\\source\\repos\\HealthcareApp\\Utilities\\ConsoleSelectionHelper.cs",\
"C:\\Users\\310511\\source\\repos\\HealthcareApp\\Utilities\\SystemTime.cs",\
"C:\\Users\\310511\\source\\repos\\HealthcareApp\\Utilities\\Validations.cs",\
"C:\\Users\\310511\\source\\repos\\HealthcareApp\\.gitignore",\
"C:\\Users\\310511\\source\\repos\\HealthcareApp\\coverage.xml",\
"C:\\Users\\310511\\source\\repos\\HealthcareApp\\obj\\HealthcareApp.csproj.nuget.dgspec.json",\
"C:\\Users\\310511\\source\\repos\\HealthcareApp\\obj\\project.assets.json",\
"C:\\Users\\310511\\source\\repos\\HealthcareApp\\.vs\\HealthcareApp.slnx\\v18\\DocumentLayout.backup.json",\
"C:\\Users\\310511\\source\\repos\\HealthcareApp\\.vs\\HealthcareApp.slnx\\v18\\DocumentLayout.json",\
"C:\\Users\\310511\\source\\repos\\HealthcareApp\\bin\\Debug\\net10.0\\HealthcareApp.deps.json",\
"C:\\Users\\310511\\source\\repos\\HealthcareApp\\bin\\Debug\\net10.0\\HealthcareApp.runtimeconfig.json",\
"C:\\Users\\310511\\source\\repos\\HealthcareApp\\obj\\Debug\\net10.0\\HealthcareApp.sourcelink.json"

151EF4F4-9CEA-BFCF-E0FE-EEFF8141403C.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\310511\\source\\repos\\HealthcareApp\\.sonarqube\\out\\0",\
"C:\\Users\\310511\\source\\repos\\HealthcareApp\\.sonarqube\\out\\2"
151EF4F4-9CEA-BFCF-E0FE-EEFF8141403C.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\310511\\source\\repos\\HealthcareApp\\.sonarqube\\out\\0\\Issues.json",\
"C:\\Users\\310511\\source\\repos\\HealthcareApp\\.sonarqube\\out\\2\\Issues.json"
151EF4F4-9CEA-BFCF-E0FE-EEFF8141403C.sonar.cs.scanner.telemetry=\
"C:\\Users\\310511\\source\\repos\\HealthcareApp\\.sonarqube\\out\\0\\Telemetry.json",\
"C:\\Users\\310511\\source\\repos\\HealthcareApp\\.sonarqube\\out\\2\\Telemetry.json"

151EF4F4-9CEA-BFCF-E0FE-EEFF8141403C.sonar.working.directory=C:\\Users\\310511\\source\\repos\\HealthcareApp\\.sonarqube\\out\\.sonar\\mod0
B3DFE11A-BA16-4676-8A27-C47DB5B99F8C.sonar.projectKey=HealthcareApp:B3DFE11A-BA16-4676-8A27-C47DB5B99F8C
B3DFE11A-BA16-4676-8A27-C47DB5B99F8C.sonar.projectName=HealthCareAppTests
B3DFE11A-BA16-4676-8A27-C47DB5B99F8C.sonar.projectBaseDir=C:\\Users\\310511\\source\\repos\\HealthCareAppTests
B3DFE11A-BA16-4676-8A27-C47DB5B99F8C.sonar.sourceEncoding=utf-8
B3DFE11A-BA16-4676-8A27-C47DB5B99F8C.sonar.sources=
B3DFE11A-BA16-4676-8A27-C47DB5B99F8C.sonar.tests=\


B3DFE11A-BA16-4676-8A27-C47DB5B99F8C.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\310511\\source\\repos\\HealthcareApp\\.sonarqube\\out\\1",\
"C:\\Users\\310511\\source\\repos\\HealthcareApp\\.sonarqube\\out\\3"
B3DFE11A-BA16-4676-8A27-C47DB5B99F8C.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\310511\\source\\repos\\HealthcareApp\\.sonarqube\\out\\1\\Issues.json",\
"C:\\Users\\310511\\source\\repos\\HealthcareApp\\.sonarqube\\out\\3\\Issues.json"
B3DFE11A-BA16-4676-8A27-C47DB5B99F8C.sonar.cs.scanner.telemetry=\
"C:\\Users\\310511\\source\\repos\\HealthcareApp\\.sonarqube\\out\\1\\Telemetry.json",\
"C:\\Users\\310511\\source\\repos\\HealthcareApp\\.sonarqube\\out\\3\\Telemetry.json"

B3DFE11A-BA16-4676-8A27-C47DB5B99F8C.sonar.working.directory=C:\\Users\\310511\\source\\repos\\HealthcareApp\\.sonarqube\\out\\.sonar\\mod1
sonar.coverage.exclusions=Program.cs,**/Program.cs,**/Data/**,**/Enums/**,**/Models/**,**/Utilities/**,**/Exceptions/**,**/Controllers/**
sonar.host.url=http://localhost:9000
sonar.cs.vscoveragexml.reportsPaths=coverage.xml
sonar.exclusions=coverage.xml
sonar.visualstudio.enable=false

sonar.modules=151EF4F4-9CEA-BFCF-E0FE-EEFF8141403C,B3DFE11A-BA16-4676-8A27-C47DB5B99F8C

